name: Ruby

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 * * * *'
jobs:
  ruby:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        repository: ytkg/toggl_to_pixela
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true
    - name: Run script
      env:
        TOGGL_API_TOKEN: ${{ secrets.TOGGL_API_TOKEN }}
        TOGGL_WORKSPACE_ID: ${{ secrets.TOGGL_WORKSPACE_ID }}
        PIXELA_USERNAME: ${{ secrets.PIXELA_USERNAME }}
        PIXELA_TOKEN: ${{ secrets.PIXELA_TOKEN }}
      run: bundle exec ruby app.rb
